/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as OrdersCodeRouteImport } from './routes/orders.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomersRoute,
} as any)
const OrdersCodeRoute = OrdersCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => OrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/automations': typeof AutomationsRoute
  '/customers': typeof CustomersRouteWithChildren
  '/finance': typeof FinanceRoute
  '/incidents': typeof IncidentsRoute
  '/inventory': typeof InventoryRoute
  '/marketing': typeof MarketingRoute
  '/orders': typeof OrdersRouteWithChildren
  '/payments': typeof PaymentsRoute
  '/settings': typeof SettingsRoute
  '/customers/$id': typeof CustomersIdRoute
  '/orders/$code': typeof OrdersCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/automations': typeof AutomationsRoute
  '/customers': typeof CustomersRouteWithChildren
  '/finance': typeof FinanceRoute
  '/incidents': typeof IncidentsRoute
  '/inventory': typeof InventoryRoute
  '/marketing': typeof MarketingRoute
  '/orders': typeof OrdersRouteWithChildren
  '/payments': typeof PaymentsRoute
  '/settings': typeof SettingsRoute
  '/customers/$id': typeof CustomersIdRoute
  '/orders/$code': typeof OrdersCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/automations': typeof AutomationsRoute
  '/customers': typeof CustomersRouteWithChildren
  '/finance': typeof FinanceRoute
  '/incidents': typeof IncidentsRoute
  '/inventory': typeof InventoryRoute
  '/marketing': typeof MarketingRoute
  '/orders': typeof OrdersRouteWithChildren
  '/payments': typeof PaymentsRoute
  '/settings': typeof SettingsRoute
  '/customers/$id': typeof CustomersIdRoute
  '/orders/$code': typeof OrdersCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/automations'
    | '/customers'
    | '/finance'
    | '/incidents'
    | '/inventory'
    | '/marketing'
    | '/orders'
    | '/payments'
    | '/settings'
    | '/customers/$id'
    | '/orders/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/automations'
    | '/customers'
    | '/finance'
    | '/incidents'
    | '/inventory'
    | '/marketing'
    | '/orders'
    | '/payments'
    | '/settings'
    | '/customers/$id'
    | '/orders/$code'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/automations'
    | '/customers'
    | '/finance'
    | '/incidents'
    | '/inventory'
    | '/marketing'
    | '/orders'
    | '/payments'
    | '/settings'
    | '/customers/$id'
    | '/orders/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  AutomationsRoute: typeof AutomationsRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  FinanceRoute: typeof FinanceRoute
  IncidentsRoute: typeof IncidentsRoute
  InventoryRoute: typeof InventoryRoute
  MarketingRoute: typeof MarketingRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  PaymentsRoute: typeof PaymentsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/orders/$code': {
      id: '/orders/$code'
      path: '/$code'
      fullPath: '/orders/$code'
      preLoaderRoute: typeof OrdersCodeRouteImport
      parentRoute: typeof OrdersRoute
    }
  }
}

interface CustomersRouteChildren {
  CustomersIdRoute: typeof CustomersIdRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersIdRoute: CustomersIdRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface OrdersRouteChildren {
  OrdersCodeRoute: typeof OrdersCodeRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersCodeRoute: OrdersCodeRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  AutomationsRoute: AutomationsRoute,
  CustomersRoute: CustomersRouteWithChildren,
  FinanceRoute: FinanceRoute,
  IncidentsRoute: IncidentsRoute,
  InventoryRoute: InventoryRoute,
  MarketingRoute: MarketingRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PaymentsRoute: PaymentsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
